spring.application.name=backend

# ===============================
# Cấu hình PostgreSQL
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/smart_workstation}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
# Dùng create khi muốn drop tạo mới
spring.jpa.show-sql=true

# ===============================
# Cấu hình Redis
# ===============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# ===============================
# Cấu hình MQTT
# ===============================
mqtt.broker.url=${MQTT_URL:tcp://localhost:1883}
mqtt.client.id=spring-boot-backend-prod

jwt.secret = ${JWT_SECRET}
jwt.expiration = 86400000
# so s 1 ngay







